# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guac_manage', '0007_auto_20170614_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
